### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by sriks6711** [Nutankumarcv/Openvino_Video-Processing#3]
how is the GPU going to be used? also, what happens when a system does not have GPU and I give '-d GPU' as argument?

**Comment by Nutankumarcv** [comment]
If we pass the argument -d "GPU," then the system will use GPU hardware. Otherwise, the default argument will be 'CPU',
so we can run both systems.

**Comment by sriks6711** [comment]
That is not correct. Passing "-d GPU" does not do anything in the code. Please check and revert

**Comment by Nutankumarcv** [comment]
Thanks for identifying, It has been fixed.
